all:
    children:
        web:
            hosts:
                3.86.145.65
            vars:
                ansible_user: ubuntu
                ansible_connection: ssh
                ansible_ssh_private_key_file: ~/.ssh/photos
                ansible_python_interpreter: /usr/bin/python3