all:
    children:
        web:
            hosts:
                34.196.195.136
            vars:
                ansible_user: ubuntu
                ansible_connection: ssh
                ansible_ssh_private_key_file: ~/.ssh/photos
                ansible_python_interpreter: /usr/bin/python3