all:
    children:
        web:
            hosts:
                52.71.170.137
            vars:
                ansible_user: ubuntu
                ansible_connection: ssh
                ansible_ssh_private_key_file: ~/.ssh/photos
                ansible_python_interpreter: /usr/bin/python3