global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - "/etc/prometheus/django.rules"

scrape_configs:
  - job_name: "django"
    metrics_path: "/g4coe94jrokt64o2avss46gp9uhjsv"
    static_configs:
    - targets:
      - lewdix.com
